server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: gateway-server

eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/