server:
  port: 0
  error:
    include-message: always

spring:
  application:
    name: product-service

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/